# This is a basic workflow to help you get started with Actions

name: Update masterList

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Update MasterList file
      run : wget "https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/ElekAusweise/CSCA/GermanMasterList.zip?__blob=publicationFile" -O- | zcat | openssl cms -inform DER -verify -noverify -out app/src/main/assets/newMasterList

    - name: Commit new masterList
      run: |
        set +e
        diff -s app/src/main/assets/masterList app/src/main/assets/newMasterList
        if [ $? -ne 0 ]
        then
        echo "Sending new masterList"
        mv app/src/main/assets/newMasterList app/src/main/assets/masterList
        git add .
        git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git commit -m "Update masterList"
        git push "https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@github.com/${{ secrets.USERNAME }}/passport-reader.git"
        fi
