# This is a basic workflow to help you get started with Actions

name: Build APK

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Update MasterList file
      run : wget "https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/ElekAusweise/CSCA/GermanMasterList.zip?__blob=publicationFile" -O- | zcat | openssl cms -inform DER -verify -noverify -out app/src/main/assets/masterList

    # Runs a single command using the runners shell
    - name: Install dependencies
      run: sudo apt-get install -y android-sdk

    - name: Setup Workspace
      run : |
        export ANDROID_SDK_ROOT=/usr/lib/android-sdk
        sudo chown -R runner:runner /usr/lib/android-sdk

    - name: Build
      run: |
        cd app
        ../gradlew build

    - name: Send to transfer.sh
      run: |
        curl --upload-file ./app/build/outputs/apk/debug/app-debug.apk https://transfer.sh/app-debug.apk
        curl --upload-file ./app/build/outputs/apk/release/app-release-unsigned.apk https://transfer.sh/app-release.apk
